### ISSUE TITLE
[FR] See "starred" artists

### ISSUE THREAD

**Issue by awsms** [ogarcia/ultrasonic#591]
There is a button to see starred albums & songs, but none for artists.

Could we also have a unified starred menu, to display all of the starred stuff on the same page?

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
