### ISSUE TITLE
Release next version

### ISSUE THREAD

**Issue by tzugen** [ogarcia/ultrasonic#650]
I suggest bumping the version code to 3, as we now have quit a lot of major changes :)
There are a few small issues and PRs left and then it should be ready for beta.

**Comment by tzugen** [comment]
OK, I think it's ready! @nitehu

**Comment by ogarcia** [comment]
I have a big problem in my device. When I go to `Artist` -> `any artist`, I can see the album list but cannot enter in albums to select songs :scream: :

![photo_2021-12-21_09-35-04](https://user-images.githubusercontent.com/572924/146897903-b54f4dc2-69a0-4709-9b28-6959a8430d45.jpg)

**Comment by tzugen** [comment]
It is displaying the albums using the track adapter.

**Comment by ogarcia** [comment]
I reopen this to add here the small last hour bugs before publish 3.0.0.

About bug described here #655 (with the scroller). I create a playlist called _Scroll Test_ in the demoserver that always have these problem (at least in my device). I think that the point is adding songs to playlist until it is slightly larger than the screen size. Anyway if cannot fix it we can live whit it without problem.
**NOTE**: Scroll bug does not happen in 2.24.0!!!

Other small bug. The main menu don't scroll. Simply open Ultrasonic, rotate your phone and try to move list up and down.

**Comment by ogarcia** [comment]
Other bug:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.moire.ultrasonic.debug/org.moire.ultrasonic.activity.NavigationActivity}: java.lang.IllegalStateException: A migration from 4 to 3 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
```

We can't downgrade from 3.0.0 to 2.24.0. I think that this is necessary since 3.0.0 will be in beta and 2.24.0 in stable channel and the users may leave the beta channel.

**Comment by tzugen** [comment]
I put a PR for the downgrade and the main scroll.
The Playlist scroll bug I still can't reproduce even with the Playlist you made

**Comment by ogarcia** [comment]
We have a big problem now with database versions.

If I run the new version the database is upgraded to version 4, but if I run current version the database must be downgraded to version 3. This downgrade cannot be done because current version (in master) don't have any method to downgrade the database and always give this error.

`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.moire.ultrasonic.debug/org.moire.ultrasonic.activity.NavigationActivity}: java.lang.IllegalStateException: A migration from 4 to 3 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.`

I think that the only thing we can do is release a intermediate 2.24.1 version that only have the ability of downgrade the database.

What do you think?

**Comment by tzugen** [comment]
Yes we can release it both at the same time. The 3.0 beta as well as the 2.24.1, which will have only the fallbackToDestructiveMigration() code added (see the open PR)

**Comment by ogarcia** [comment]
The problem with `fallbackToDestructiveMigration()` is that a downgrade causes all your settings to be lost and that is bad. I do a new PR #660 to avoid this, what do you think?

**Comment by ogarcia** [comment]
All done :tada:

**Comment by ogarcia** [comment]
@nitehu @tzugen Info: the app is published in play store, but is _on hold_ because the revision bot thinks that the app is not compliant with Google Play Policies, specific:
Your app contains content that doesn't comply with the Unauthorized Use of Copyrighted Content policy.

I have opened a case to a person perform the review, but for now I'm waiting

**Comment by nitehu** [comment]
??? copyrighted content? That's really strange...

**Comment by ogarcia** [comment]
I don't know why, I have asked them for explanations anyway

**Comment by tzugen** [comment]
I had a look at the console, no ptrogess so far :(

**Comment by ogarcia** [comment]
Lately Google is mastering in [touching the balls of its users](https://news.ycombinator.com/item?id=29996432). The only thing that we can do is wait or can deploy new versions and pray to pass the filter.

**Comment by ogarcia** [comment]
I just got an email from Google :hankey: that simply says we need to upload a new version :shrug:

I think that we can merge any minor change as #665 or #648 and upload it as 3.0.1 to try again.

**Comment by nitehu** [comment]
I've merged #671, is that ok for a new release? The PRs related to the new kotlin version are throwing an exception now because of Koin, and will need a bit more work.

**Comment by ogarcia** [comment]
@nitehu Yes, along this week I will do 3.0.1 with the #671

**Comment by ogarcia** [comment]
@nitehu @tzugen 3.0.0 is now pubished!!! Seems that Google finish the review :shrug: Anyway I published a 3.0.1 version that (I think) will be approved in next hours.

We can now revert the database changes to update it and start work in 3.1.0 :wink:

**Comment by nitehu** [comment]
I've added back server coloring in #678 
@ogarcia do you want to release a version with this, or should we proceed with the other PRs before that?

**Comment by ogarcia** [comment]
@nitehu As you wish, this weekend I'm afk so if you prefer you can add more PRs
