### ISSUE TITLE
Feature request: option to change language

### ISSUE THREAD

**Issue by tanrak** [ogarcia/ultrasonic#669]
The translations are very different in terms of quantity and quality.
Furthermore, in version 3, the gender stars have found their way into the German translation. Regardless of what I think of them, they are very inconsistent. Sometimes they are present and at other places they are not present.
I think these are enough reasons to integrate an option for language selection independent of the set system language.

**Comment by ogarcia** [comment]
@tanrak instead of request an option to change lenguage why not help in translation [here](https://www.transifex.com/ultrasonic/ultrasonic/)? It's too easy and you don't need install anything.

**Comment by tanrak** [comment]
Certainly that would be an option. But I think that, for example, the gender stars in the German translation would lead to a controversial discussion. Personally, I would remove them. For others, however, the gender stars are important.
Perhaps a compromise would be to simply choose the English language as a fallback, as the Simple Mobile Tools developer has implemented in his apps.

**Comment by ogarcia** [comment]
Sorry, but I don't understand you when you say "gender stars". Can you show me what is the line into [this file](https://github.com/ultrasonic/ultrasonic/blob/develop/ultrasonic/src/main/res/values/strings.xml) with the _conflicting string_ (or strings)?

**Comment by tanrak** [comment]
For example in the german string file: `<string name="common.artist">Künstler*in</string>`.
More about this, for example, in [Wikipedia](https://en.wikipedia.org/wiki/Gender_star). The Gender-neutral language is controversially discussed in Germany.

**Comment by tzugen** [comment]
Yes, I added them and would like to keep them as i am non-binary as well.
For non german speakers, (nearly) all german nouns are gendered, and Künstler is the male version, while Künstler*innen is a writing that includes all genders. 

Spotify has done the same, btw.

**Comment by tanrak** [comment]
In this context, "Künstler" is the generic he and as well includes all genders. But these discussions can be avoided if, for example, the user can select the English language as a fallback if he does not want to see the gender stars.

**Comment by ogarcia** [comment]
IMHO, and from the most absolute respect. I think that if gender star is not officially supported by royal academy of language (or similar in german), it should be avoided.
In spanish we have similar problem and we solve it using the official ways. If in future our royal academy of language accept our form of non-binary gender then we use it but for now is only a proposal (which we don't like very much by the way since it deforms the language too much).

**Comment by tzugen** [comment]
We won't finish this discussion here, I agree with @tanrak.
No harm in adding a language switch into the preferences

**Comment by paroj** [comment]
I just wanted to say that I removed the gender-star, while I was updating the German translation before noticing this issue.

My proposal would be to leave it that way and add a "gendered" german variant when implementing this issue, so people can opt-in to use it - similar to how things work in "real-life".

**Comment by tzugen** [comment]
I am unsure if I will continue developing here. 

I did not have expected that this would meet such a large backlash.
In many other UI features we used to look how other apps like Spotify etc. used to solve it. Spotify has taken exactly the same approach as I had proposed. But that doesn't seem to matter now. Ogarcia suggested to look what the "official" language guidelines say. And the Duden, the institution writing guidelines about the German language. has a section on different gendering forms. So it can also not be said that this would be inofficial or incorrect. 

Attitudes like this just continue to make tech a male-dominated space 😔

**Comment by ogarcia** [comment]
I agree with @tzugen If the official institution approves the use of any form, then it can be used without problem

**Comment by paroj** [comment]
@tzugen I think we can agree that the issue is controversial. This means there is no definitive, "correct" answer. Obviously, I have a different view and as such do not come to your conclusions.
Lets leave it at that, as I dont think further discussion will lead us anywhere.

@ogarcia What we can say is that there is a change that some people are unhappy about. My guess is that there will be many more once this hits the Play Store. So whatever the decision you make, you should be able to stand by it.

[As far as I understand, the Duden currently only provides an overview of the forms, without standardizing them.](https://www-duden-de.translate.goog/sprachwissen/sprachratgeber/Geschlechtergerechter-Sprachgebrauch?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp)

**Comment by paroj** [comment]
@tzugen could you please refrain from silently changing the translation back? As far as I can tell there is no consensus regarding the issue yet. Also there was no public discussion when you changed it in the first place.

**Comment by tzugen** [comment]
I was not the one who started modifying them while people were discussing it here.
As I said, the spelling is allowed by the Duden, used by Spotify, used by Twitter and I don't understand why we need to be more conservative than big tech

**Comment by paroj** [comment]
yes, you modified them without any prior discussion and after I started that discussion, you went back and locked it to the way you want it. :+1: 

The Duden is merely a commercial dictionary. Even so, it does not explicitly allow that spelling, but merely *documents* it. Different things.
The normative entity is called "Rat für deutsche Rechtschreibung" and that one explicitly states that the gender-star stuff should be avoided
https://www.rechtschreibrat.com/geschlechtergerechte-schreibung-empfehlungen-vom-26-03-2021/

**Comment by tzugen** [comment]
@paroj
I have never seen you being active here before and now you continue this very divise discussion. 
We have signaled before that a menu which enables users to pick their preferred language would be an acceptable idea. You are welcome to contribute to this project for example by creating a PR that adds this preference. It should be a relatively easy to code change. But going on with it in this way is just taking the time and energy of the people that maintain this project.

**Comment by ogarcia** [comment]
@tzugen I think this issue should be left open until the feature is implemented. The topic of this issue is add an option to change language, if we close it it seems to be already implemented.

I have reopened and locked to avoid the off-topic.

**Comment by ogarcia** [comment]
I have been trying to find out a bit about this (from my lack of knowledge of the German language) and I am concerned about a couple of points:

First for all, Duden says: "Vom amtlichen Regelwerk nicht abgedeckt sind Schreibweisen wie die folgenden" which my translator interprets as "Spellings such as the following are not covered by the official regulations". I don't know if my translator is translating this phrase properly, but if so then we are in conflict with what I initially commented:

> IMHO, and from the most absolute respect. I think that if gender star is not officially supported by royal academy of language (or similar in german), it should be avoided.

Although, as I said, I am using an automatic translator and I could be wrong.

However, my concern is more about accessibility. Does this proposal work well with screen readers? I say this because in Spanish the proposals made so far neither work with readers nor are they accessible.

@tzugen Could you check this last one?

**Comment by tzugen** [comment]
OK, I can check it out...

Do you know what screen readers are common in Android?

**Comment by ogarcia** [comment]
As I know the most importat is included in Android by defatult in settings -> accessibility -> screen readers

**Comment by ogarcia** [comment]
@tzugen there is a suggestion of @hmueller01 that says to use **Interpreten**. What do you think about this?

As I said before, I don't know german, but I can see that sometimes Artist is translated as **Künstler*innen** and sometimes as **Interpreten**, what appears to be a translation style problem (IMHO should have a unified style):
![artist german translations](https://user-images.githubusercontent.com/572924/158333171-4df9275e-e5e0-430a-b71b-fa25d4e559a4.png)

**Comment by tzugen** [comment]
I checked out the TTS. It leaves a short break instead of the star, which is how you would pronounce it when speaking as well.

![Bildschirmfoto von 2022-03-19 10-01-41](https://user-images.githubusercontent.com/67737443/159114902-1a69cbe3-9783-45e3-a4cc-21cc7b96418c.png)

this is how spotify does it.
