### ISSUE TITLE
Keep Now Playing list content when swithching to offline and then back online

### ISSUE THREAD

**Issue by tw1015** [ogarcia/ultrasonic#670]
### ## Problem description
If I start playing a list of songs (random or selected) there will be 5 songs downloaded in advance, the others are in the list waiting their turn to be downloaded. If I switch to offline mode and then go to the "Now Playing" section I will only see the downloaded songs, this seems normal. But if I then switch back to online mode the original playlist is gone and all I have are the downloaded songs. This seems to be a bug, I woud expect to find the original list of songs I started with whil online.

### Steps to reproduce

Create a random list of songs to play and verify they are visible by going to "Now Playing". 
Go back to the main menu and switch to offline mode. In "Now Playing there should only be the songs that were downloaded from the list ( or possibly others from an earlier time). 
Go back to online mode and go to "Now Playing" and there will only be the downloaded songs from the recently created list of songs, all other songs from the original list are gone.

## System information

 * **Ultrasonic version**: *version of the app* 3.0.0
 * **Android version**: *Version of Android OS on the device* 12
 * **Device info**: *Device manufacturer, model* Pixel 4a and Samsung Tab S7

## Additional notes

I don't recall this behaviour with version 2.23 from which I upgraded to V. 3.0.0

**Comment by tw1015** [comment]
So I  verified on 2.23 and 2.24 and both do the same behavior.

**Comment by nitehu** [comment]
Thank you for reporting this!
Currently Ultrasonic works this way by design.
Ultrasonic only stores a single "now playing list". When the offline mode is selected, the songs which aren't available are removed from this list (if it would keep them, they would be skipped with an error anyway). When a server is selected again, Ultrasonic doesn't know what was the previous list (neither that it has connected back to the previous server or a new one), so it can't restore the list.

This issue can be a new feature request, however I'm not currently sure how this feature would be implemented. 
A separate now playing list could be maintained for every server (and the offline mode too). As I remember we've talked about something similar, when the storage of the now playing list is moved from file to the DB.

**Comment by ogarcia** [comment]
See #718
