### ISSUE TITLE
Server goes to offline mode when changing media folder

### ISSUE THREAD

**Issue by tw1015** [ogarcia/ultrasonic#677]
## Problem description

When switching between media folders i.e. music -> video the server selected changes to offline mode.

### Steps to reproduce

Select your online server
Open media library ... select folder and change to a different folder
The Server selection is now offline

## System information

 * **Ultrasonic version**:  3.0.0
 * **Android version**: * 12 - Pixel 4a

## Additional notes

Airsonic Advanced 11.0.0-SNAPSHOT.20220124042650

**Comment by tw1015** [comment]
FYI,  I dont see this in v2.24.

**Comment by ogarcia** [comment]
Please, check with latest beta. If still present, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
