### ISSUE TITLE
Feature request: separate "songs to preload" for Wifi and Mobile

### ISSUE THREAD

**Issue by Bomfunk** [ogarcia/ultrasonic#716]
## Problem description

It would be great to have different settings for "Songs To Preload" for Wifi and Mobile.
For example, to save data I could allow to preload only 1 next song on Mobile, while on Wifi I could put "Unlimited" so it caches as much as possible before I get off the network.

### Steps to reproduce

Go to settings and observe only single "Song To Preload" setting.

### Ultrasonic client

 * **Ultrasonic version**: 3.1.1 (from F-Droid)
 * **Android version**: 11, OxygenOS
 * **Device info**: OnePlus 8

### Server

 * **Server name**: Airsonic Advanced
 * **Server version**: 11.0.0
 * **Protocol used**: https letsencrypt

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
