### ISSUE TITLE
Feature: ReplayGain support

### ISSUE THREAD

**Issue by abdulocracy** [ogarcia/ultrasonic#732]
## Problem description

It would be great if Ultrasonic had support for ReplayGain tags. Many music streaming apps have options for volume normalization, and this could be recreated in Ultrasonic with this feature.

### Ultrasonic client

 * **Ultrasonic version**: 3.2.0
 * **Android version**: 12L
 * **Device info**: Pixel 4a

### Server

 * **Server name**: LMS
 * **Server version**: 3.28.0
 * **Protocol used**: https let's encrypt

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
