### ISSUE TITLE
Feature: Export/import application settings

### ISSUE THREAD

**Issue by fexofenadine** [ogarcia/ultrasonic#741]
## Problem description

With the large, and increasing number of settings in the application it would be wonderful if there was an option to export/backup and import/restore all the settings at once.

Would make reinstalls, setting up new phones and duplicating devices painless.

Some apps with this function offer hooks to Google Drive or other clouds but that's just gravy at this point.

### Ultrasonic client

 * **Ultrasonic version**: 3.2.0
 * **Android version**: 13 (beta)
 * **Device info**: Pixel 6 pro

### Server

 * **Server name**: Airsonic Advanced
 * **Server version**: 11.0.0-SNAPSHOT.20220418221611
 * **Protocol used**: https letsencrypt

**Comment by tzugen** [comment]
There is a PR to add support for the native backup functionality as a first step...

**Comment by ogarcia** [comment]
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.
